name: 'Code Coverage'
description: 'Publish coverage report to a PR & enforce coverage on new & modified files'
author: 'zimosworld'
inputs:
  coverageFile:
    required: true
    description: 'local path to a coverage xml file like the output of pytest --cov'
  token:
    required: true
    description: 'github token'
  thresholdAll:
    required: false
    description: the coverage threshold for average over all files [0,1]
    default: 0.0
  thresholdNew:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.0
  thresholdModified:
    required: false
    description: the coverage threshold for average over new files [0,1]
    default: 0.0
  sourceDir:
    required: false
    description: the directory to use as the source of the coverage report
  passIcon:
    required: false
    description: the indicator for files that passed
    default: '🟢'
  failIcon:
    required: false
    description: the indicator for files that failed
    default: '🔴'
  commentTitle:
    required: false
    description: the title of the comment added to the PR
    default: 'Pull Request Code Coverage'
  shouldCountRenamedAsModified:
    required: false
    description: switch to count renamed files as modified
    default: 'true'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
   icon: 'umbrella'
   color: 'purple'
